spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
#          In order to use Route locator only -->
          enabled: false
          lowerCaseServiceId: true

#  Enable All Endpoints in Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Bank System Gateway server Application"
    version: "1.0.0"

logging:
  level:
    com:
      bmc:
        gatewayserver: DEBUG
