spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
#          In order to use Route locator only -->
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

#  Enable All Endpoints in Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: $(spring.application.name)

info:
  app:
    name: "gatewayserver"
    description: "Bank System Gateway server Application"
    version: "1.0.0"

logging:
  level:
    com:
      bmc:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
#      indicates how many requests should be monitored until it change the state of circuit breaker from close to open
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
#      at least 50 percent of requests are failed then the circuit breaker can move from open state to close state
      failureRateThreshold: 50
#      The circuit breaker pattern is going to wait 10 seconds whenever it tries
#      to move to half open state and allow the partial traffic.
      waitDurationInOpenState: 10000