spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to Bank loans related Local APIs "
  contactDetails:
    name: "Masi - Developer"
    email: "masi@gmail.com"
  onCallSupport:
    - 123456
    - 789654


