build:
  version: "2.0"

cards:
  message: "Welcome to Bank cards related Local APIs "
  contactDetails:
    name: "Masi - Developer"
    email: "masi@gmail.com"
  onCallSupport:
    - 123456
    - 789654