server:
  port: 8080
spring:
  application:
    name: accounts
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root

  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
#    "optional" keyword: It tells to this service if it is not
#  able to connect to config server, it can still continue
#  run this service.
    import: "optional:configserver:http://localhost:8071/"

#To prevent building rabbitMq container because of the OS speed
#  rabbitmq:
#    host: mybroker.com
#    port: 5672
#    username: user
#    password: secret


#  Enable All Endpoints in Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"