spring:
  application:
    name: "configserver"
#  ?native? profile does not use Git but loads the config files
#    from the local classpath or file system
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"

  rabbitmq:
    host: mybroker.com
    port: 5672
    username: user
    password: secret


server:
  port: 8071

#  Enable All Endpoints in Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
