server:
  port: 9010

spring:
  application:
    name: message
# invoke both email and sms function as a single logical unit "emailsms"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
#          any message comes to this queue destination will be redirected to spring.cloud.function.destination.email|sms
          destination: send-communication
          group: $(spring.application.name)
        emailsms-out-0:
          destination: communication-sent

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s